- name: ansible variable data types
  hosts: localhost
  vars:
  - AGE: 30 #numbers
  - NAME: siva #sting
  - isDevOps: true #boolean
  - skills:  #list
  - DevOps
  - Aws
  - Docker
  - EXPERIENCE:  #map
  DevOps: 7
  Aws: 5
  Docker: 4
  tasks:
  - name: print number variable
    ansible.builtin.debug:
     msg: "{{AGE}}"
  - name: print number variable
    ansible.builtin.debug:
     msg: "{{NAME}}"
  - name: print number variable
    ansible.builtin.debug:
     msg: "{{isDevOps}}"
  - name: print number variable
    ansible.builtin.debug:
     msg: "{{skills}}"
  - name: print number variable
    ansible.builtin.debug:
     msg: "{{EXPERIENCE}}"


