- name: copy {{component}} service
  ansible.builtin.copy:
    src: "{{component}}.service"
    dest: /etc/systemd/systey {{component}}.service
  
- name: deamon reload
  ansible.builtin.systemd:
    daemon_reload: true
    state: restarted
    name: "{{component}}"
