- name: configureing mongodb
  hosts: mongodb
  tasks:
  - name: copy mongo repo to yum.repos.d
    ansible.builtin.repo:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb
    ansible.builtin.yum:
      name: mongodb-org
      state: installed

  - name: Start and enable mongodb
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes

  - name: update listen address
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: restart service 
    ansible.builtin.service:
      name: mongod
      state: restarted
     
